# Generated by Django 4.0.2 on 2022-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiznameques', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherassigname', models.CharField(max_length=50)),
                ('quizname', models.CharField(max_length=50)),
                ('totalnumofmarks', models.BigIntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentname', models.CharField(max_length=50)),
                ('studentemail', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('studentrollno', models.BigIntegerField(verbose_name=20)),
                ('studentpass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teachername', models.CharField(max_length=50)),
                ('teacheremail', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('teacherpass', models.CharField(max_length=50)),
            ],
        ),
    ]
