# Generated by Django 4.0.2 on 2022-03-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_questions_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Quiz_Name',
            new_name='quiznameques',
        ),
    ]
