# Generated by Django 4.0.2 on 2022-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=100)),
                ('Quiz_Name', models.CharField(max_length=300)),
                ('Score', models.CharField(max_length=100)),
                ('Percentage', models.CharField(max_length=100)),
                ('Correct', models.CharField(max_length=100)),
                ('Incorrect', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
            ],
        ),
    ]
