# Generated by Django 4.0.2 on 2022-03-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quizreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizreport',
            name='Question',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AddField(
            model_name='quizreport',
            name='Selected_Ans',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
