# Generated by Django 4.0.2 on 2022-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quizreport_question_quizreport_selected_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=100)),
                ('Quiz_Name', models.CharField(max_length=300)),
                ('Question', models.CharField(default=1, max_length=300)),
                ('Selected_Ans', models.CharField(default=1, max_length=300)),
            ],
        ),
    ]
