# Generated by Django 4.0.2 on 2022-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_answer_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinfo',
            name='time',
            field=models.BigIntegerField(default=5),
        ),
    ]
