# Generated by Django 4.0.2 on 2022-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_quizinfo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinfo',
            name='time',
            field=models.BigIntegerField(default=5),
        ),
    ]
