# Generated by Django 4.0.2 on 2022-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_quizinfo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizreport',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='quizreport',
            name='Selected_Ans',
        ),
    ]
