# Generated by Django 4.0.2 on 2022-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_quizreport_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinfo',
            name='totalnumofmarks',
        ),
        migrations.AddField(
            model_name='quizinfo',
            name='Duedate',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='quizinfo',
            name='Time',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
