# Generated by Django 4.0.2 on 2022-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_quizinfo_totalnumofmarks_quizinfo_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizreport',
            name='Total_Marks',
            field=models.CharField(default=10, max_length=100),
        ),
    ]
