# Generated by Django 4.0.2 on 2022-04-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_quizreport_total_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizreport',
            old_name='Quiz_Name',
            new_name='QuizName',
        ),
    ]
