# Generated by Django 4.0.2 on 2022-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_quiz_name_quizreport_quizname'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_bank',
            name='Option1',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='answer_bank',
            name='Option2',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='answer_bank',
            name='Option3',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='answer_bank',
            name='Option4',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='answer_bank',
            name='answer',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='answer_bank',
            name='marks',
            field=models.BigIntegerField(default=1, max_length=3),
        ),
    ]
