# Generated by Django 4.0.2 on 2022-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_answer_bank_option1_answer_bank_option2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('qname', models.CharField(max_length=50)),
                ('isattempted', models.BooleanField(default=False)),
            ],
        ),
    ]
