# Generated by Django 4.0.2 on 2022-04-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_attemptedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Teacher',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
