# Generated by Django 4.0.2 on 2022-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinfo',
            name='totaltime',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
