# Generated by Django 4.0.2 on 2022-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_quizinfo_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_bank',
            name='Selected_Ans',
            field=models.CharField(default=1, max_length=300, null=True),
        ),
    ]
