# Generated by Django 4.0.2 on 2022-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_answer_bank_selected_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinfo',
            name='noofquest',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
