# Generated by Django 4.0.2 on 2022-04-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_quizinfo_noofquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_bank',
            name='Teacher',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='attemptedquiz',
            name='tname',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='quizreport',
            name='Teacher',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
