# Generated by Django 4.0.2 on 2022-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_answer_bank_teacher_attemptedquiz_tname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizreport',
            name='Date',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='quizreport',
            name='Time',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
