# Generated by Django 4.0.2 on 2022-04-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_quizreport_date_quizreport_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
    ]
