# Generated by Django 4.0.2 on 2022-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_answer_bank_teachername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_bank',
            name='TeacherName',
        ),
        migrations.AddField(
            model_name='quizreport',
            name='TeacherName',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
